# Generated by Django 6.1.1 on 2026-09-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_match_player1_remove_match_player2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='p1_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p2_id',
        ),
        migrations.AddField(
            model_name='match',
            name='p1_username_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_username_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='api.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
